### ISSUE TITLE
Error with npm start

### ISSUE THREAD

**Issue by jmrosdev** [islittle/create-react-app-redux-sass#1]
Hi! I installed the dependencies with npm install and when doing npm start I get this error

`/scripts/start.js:23
const {
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:136:18)
    at node.js:972:3
error Command failed with exit code 1.`

**Comment by islittle** [comment]
@jmrosdev What version of node do you use? You can see if the dependency of babel-loader is installed.It's possible that your ES6 translation plug-in has not been installed or installed successfully!
